dbt_grc:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: precise-ego-447319-h7
      dataset: dbt_dw # You can also use "schema" here
      threads: 4 # Must be a value of 1 or greater 
      keyfile: C:\Users\FULVIOBARBOSA\.dbt\precise-ego-447319-h7-8c4aec5030db.json

